apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    wal_level = replica
    max_wal_senders = 5
    wal_keep_size = 16MB
    # Additional settings as needed
  pg_hba.conf: |
    host    replication     replicator      0.0.0.0/0      md5