apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
spec:
  selector:
    matchLabels:
      app: goapp
  replicas: 2
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: muhammadhaseem/file_go:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password123"
        - name: DB_NAME
          value: "postgres"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: goapp
spec:
  selector:
    app: goapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort
